### ISSUE TITLE
No esta la información que debería de haber en espais_expositius

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#1]
He estado mirando los endpoints del proyecto para ver cual es el que se asemeje a espais para poder hacer el POJO, y me he dado cuenta que es la de espais_expositius, y no es que añada alguna variable más de la que pide que no pasaría nada (como aforament), sino que no están las variables mínimas que pide (como la media global, el teléfono, las modalidades que ofrece, etc).

**Comment by DawidPelc** [comment]
la media global es un campo calculado a partir de las valoraciones de la tabla "comentaris", aún tenemos que añadirla. En nuestro caso las modalidades se relacionan con una obra y no con un espacio. Nosotros no tenemos especificaciones de campos obligatorios, si nos decís que campos necesitais en la tabla los añadiremos.
