### ISSUE TITLE
No permite modificar servicios

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#11]
He mirado la parte de servicios y te deja hacer de todo menos modificar el servicio.
Tambien he visto que a la hora de borrar un servicio lo hace pero no dice si ha ido bien o no, seria mejor que mandara un mensaje

**Comment by DawidPelc** [comment]
Ahora ya sale un mensaje cuando se borra un servicio, acabo de provar de modificar un servicio y me ha dejado, comprobadlo de nuevo y me decís.
![editar_servei](https://user-images.githubusercontent.com/77160788/154749835-a5663252-5311-4ff0-9859-43994de5cc3b.png)

**Comment by spdvi** [comment]
@Ballesito has comprobado si funciona bien? ¿Pueden cerrar el Issue?
