### ISSUE TITLE
Paginación de Obras/Exposiciones/Museo (Offset y limit)

### ISSUE THREAD

**Issue by AlexisEvol** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#12]
Saludos

Queremos pedirles si sería posible añadir un endpoint para cada que devuelva X cantidad de obras, exposiciones y museos por favor.

Gracias por su tiempo y que tenga un buen día

**Comment by DawidPelc** [comment]
Hecho, ahora deberéis de añadir a las url /paginar/{cantidad}, siendo cantidad el número de unidades que queréis por página. Lo podés consultar en la página de ayuda con todas las rutas.
