### ISSUE TITLE
Puedes borrar un user sin token

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#13]
He estado probando el delete pero siempre mandaba el token, pero ahora he probado a hacerlo sin el token y me deja igual.

**Comment by DawidPelc** [comment]
Solucionado, ahora sin token lo único que puedes hacer es crear un usuario y tienes que ser administrador para poder editar o eliminar usuarios.

**Comment by Ballesito** [comment]
Perfecto, si podeis actualizar con todas modificaciones que habeis hecho desde la ultima vez la documentacion pls
