### ISSUE TITLE
Error al modificar el user

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#14]
Si creas un user con solo los parametros de email, password y si es admin o no va perfecto, pero a la que lo modificas para que tenga un nombre, DNI, etc no te deja luego iniciar sesion.
![image](https://user-images.githubusercontent.com/77398602/156388389-5a1754ad-9e5d-4ff0-8787-f2f5e4985f66.png)

Tambien, si creas un user con todos los paremetros te deja iniciar sesion va perfecto, pero si buscas en todos los users o en el user concreto, hay muchos parametros que se ponen en null, pero al modificarlo, pasando todos los paremetros igual menos el que quieres cambiar, si que te sale su información pero claro, como en el primer parrafo, luego no puedes iniciar sesion con ese user.

Pls corregid todo.

**Comment by DawidPelc** [comment]
Los métodos de los usuarios estaban bastante mal,  prueba ahora a ver que tal.

**Comment by Ballesito** [comment]
He probado a hacer lo mismo y nada, es decir, he creado un user con solo el correo, password y si es admin o no y si inicio sesión va bien, pero si luego modifico ese user poniéndole los demás datos se rompe.
Me he fijado que cuando creas un user, en la password sale cifrada, pero cuando lo modifico la passwod sale lo que le he puesto, no se si es por que en algún lado se cifra y en otro sitio no y peta o algo así, si podéis quitad el cifrado de la password y que sea texto plano y pruebo de nuevo a ver si era eso, o mirad que puede ser.
Gracias seguid así ^^.

**Comment by DawidPelc** [comment]
Creo que lo que pasaba era que efectivamente al editar el password no se cifraba, ahora debería de ir bien. Las password tienen que estar cifradas porque tenemos ese requisito, pero ahora debería de funcionar bien, prueba a ver si te va.

**Comment by Ballesito** [comment]
Ahora si que me va, lo que pasa es que necesitamos saber las contraseñas, ya que hay un user que administra los demás users y al mostrar la contraseña pues sale cifrada y tal, y así no podrá modificar ningún user.
He intentado modificar un user entero sin pasarle por parámetro la contraseña, pero me da error luego al hacer el login, así que necesitaríamos saber las contraseñas.

**Comment by DawidPelc** [comment]
Ahora sí que deberíais de poder modificar un usuario sin cambiar la contraseña sin que se corrompa el usuario. Si le pasas una contraseña se cifra automáticamente y si no se la pasas no se cambia. En cuanto a mostrar las contraseñas me da que no va a poder ser. El sistema funciona de manera que al introducir una contraseña esta se cifra, y al iniciar sesión se cifra la contraseña introducida y se compara con la que hay en la base de datos, ya que por motivos de seguridad no se puede mostrar.

**Comment by Ballesito** [comment]
Sisi claro, ya he probado si va bien modificar un user pasando y sin pasar la contraseña y en principio va todo bien, si veo que va mal en algún lado te aviso.
Gracias
