### ISSUE TITLE
Actualizar la info de get usuaris

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#15]
Cuando haces ese get, si has creado un usuario con todos los datos, te salen en null, pero si buscas por su id te muestra su informacion.
Tambien debeis poner que salga si es admin o no y la contraseña sin cifrar.
Gracias

**Comment by DawidPelc** [comment]
El dato de admin y el resto de datos ya salen correctamente, lo de la contraseña lo tendremos que mirar

**Comment by Ballesito** [comment]
Okey, pues cuando lo tengáis avisad y lo miro
