### ISSUE TITLE
Nuevo endpoint para espais_expositius

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#16]
Podríais poner pls un nuevo endopoint para que devuelva los espais por el tipo, es decir, que le mande de parámetro la string "museo" y me devuelva todos los espais que en tipus sea museo, y pues así con todos los tipus vaya.
Muchas gracias.

**Comment by DawidPelc** [comment]
Hecho, puedes hacer la petición a /espais_expositius/pertipus/{tipus_id}, siendo tipus_id, el ID del tipo deseado, por ejemplo 1=Museu
