### ISSUE TITLE
Token multiple

### ISSUE THREAD

**Issue by AdrianGonzalezB** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#17]
Al iniciar sesion con 2 usuarios diferentes, el primer token se invalida completamente, es decir solo deja tener 1 sesion iniciada al mismo tiempo, se deberia poder tener a mas de 1 usuario conectado a la api.
Se agradeceria el cambio en esto para seguir trabajando sin necesidad de estar logueando cada 2x3.

**Comment by spdvi** [comment]
@AdrianGonzalezB yo he accedido con 2 usuarios diferentes desde Postman simultaneamente y ahora funciona bien.

**Comment by DawidPelc** [comment]
Nosotros trabajamos con varios usuarios a la vez y nos funciona, los token no se eliminan a menos que hagas logout, pero si vuelves a iniciar sesión el token se reinicia.
