### ISSUE TITLE
Nuevos End-Points para Obras

### ISSUE THREAD

**Issue by AlexisEvol** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#18]
Saludos,

Sería posible si no es molestia añadir unos end-points para poder recibir las obras en base a: 
- Autor
- Titol
- Modalidad
- AnyCreacio

Gracias por tu tiempo y que tengas un buen día!

**Comment by DawidPelc** [comment]
Mañana nos ponemos con ello

**Comment by DawidPelc** [comment]
Hecho, podéis consultar los GET en la ayuda.
