### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#19]
Hola, en la ultima parte de la ayuda que son los comentarios (aunque pone usuaris otra vez) dice que hay un parametro que creo que es descripcio, pero luego no esta en los get ni nada, podriais ponerlo pls?

**Comment by DawidPelc** [comment]
Ya está corregido, era valoración que es un número del 1 al 5 en vez de descripción. Cuando hagáis get también os sale la fecha del comentario que es un campo que se calcula solo, y el autor del comentario basado en su autor_id, lo pusimos para un requisito nuestro pero alomejor os sirve también.
