### ISSUE TITLE
Falten camps dels espais_expositius

### ISSUE THREAD

**Issue by sergicladeraben** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#2]
Hola bones tardes.
Revisant la API ens hem donat conta que mos falten camps com per exemple el de valoració, aquest en els espais hauria de sortir-ne la mitjana, el Json que ens hauria de retornar hauria de tenir els següents camps: 
![image](https://user-images.githubusercontent.com/77398698/154316598-65e6956b-e0db-4d95-8a52-d4707c38a55d.png)

La valoració s'ntrodueix a través dels comentaris, aquest camp tambe hauria de ser afegit alla.
Gracies.

**Comment by sergicladeraben** [comment]
Les modalitats i els tipus haurien d'apereixer el nom i no l'id de cara a presentarlos a la nostre app.

**Comment by DawidPelc** [comment]
Començam ara per aquí, segons aniguem realitzant els canvis us avisarem, a mem si per aquest cap de setmana podem tenir-ho fet.

**Comment by sergicladeraben** [comment]
D'acord moltes gracies.

**Comment by DawidPelc** [comment]
Podeu comprovar l'espai expositiu 1 a veure si vos pareix correcte el nou format 
http://www.dawidpelc.com/api/laravel_projecte_baleart-dawidmateujulia/public/api/espais_expositius/1

**Comment by sergicladeraben** [comment]
Aixi esta benissim, moltes gracies per la vostra colaboració i disculpau les molesties.
