### ISSUE TITLE
Algunas imágenes repetidas

### ISSUE THREAD

**Issue by AlexisEvol** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#20]
Saludos,

Esto no es una necesidad pero eso un detalle por si queréis cambiarlo, hay algunas imágenes que están repetidas, por ejemplo la de la obra Moloko y Tête de femme

Gracias por todo! <3

**Comment by DawidPelc** [comment]
Gracias! Lo tendremos en cuenta.
