### ISSUE TITLE
Post imagenes de obras

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#21]
He intentado subir una imagen a una obra y siempre me sale lo mismo:
![image](https://user-images.githubusercontent.com/77398602/157871098-a497136b-6f88-4808-9a25-cee2ef23bcd9.png)
Me gustaría saber que formato de imagen necesita la imagen para que se pueda subir, rollo tamaño máximo y si solo puede ser .jpg, etc.
La foto que he intentado subir han sido .jpg.

**Comment by DawidPelc** [comment]
El tamaño máximo son 10 MB y se pueden subir tanto imágenes png, jpg y bmp, seguramente la imagen sea demasiado grande.

**Comment by Ballesito** [comment]
En principio las fotos que he usado son de pocos KB, pero probaré de nuevo a ver. Deben tener un tamaño en pixeles concreto? Tipo 100x100 o algo así?

**Comment by DawidPelc** [comment]
No, no hay ningún requisito así

**Comment by Ballesito** [comment]
Okay, pues cuando solucionéis el error lo pruebo a ver, pero en principio ya cumplía la imagen con lo que decís.

**Comment by Ballesito** [comment]
Me sigue dando error. El método que uso es este:
![image](https://user-images.githubusercontent.com/77398602/157909374-856ddd13-735c-4d79-9d4d-09c13e624665.png)
Con el método así el error que me da es 404 
He intentado cambiar y ponerle "imatge" que es el nombre que hay en la ayuda y no "url" a ver si hacía algo y me da este error:
500
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ddb181459`.`fotografies_obres`, CONSTRAINT `pk_fk_fotografia_obra_id` FOREIGN KEY (`obra_id`) REFERENCES `obres` (`id`)) (SQL: insert into `fotografies_obres` (`obra_id`, `id`, `descripcio`, `url`) values (0, 1, Obra 0 foto 1, http://www.dawidpelc.com/api/laravel_projecte_baleart-dawidmateujulia/public/imatges/obres/obra_0_foto_1_1647016775.jpg)) in file /hosting/www/dawidpelc.com/public/api/laravel_projecte_baleart-dawidmateujulia/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 712

Quiero entender que poniendo "imatge" es como deber ser y os habéis equivocado (creo) en como hacer eso. Miradlo y decidme ^^

**Comment by Ballesito** [comment]
500
<!doctype html>
<html class="theme-light">
<!--
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ddb181459`.`fotografies_obres`, CONSTRAINT `pk_fk_fotografia_obra_id` FOREIGN KEY (`obra_id`) REFERENCES `obres` (`id`)) (SQL: insert into `fotografies_obres` (`obra_id`, `id`, `descripcio`, `url`) values (0, 1, Obra 0 foto 1, http://www.dawidpelc.com/api/laravel_projecte_baleart-dawidmateujulia/public/imatges/obres/obra_0_foto_1_1647016775.jpg)) in file /hosting/www/dawidpelc.com/public/api/laravel_projecte_baleart-dawidmateujulia/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 712

Quiero entender que poniendo "imatge" es como deber ser y os habéis equivocado (creo) en como hacer eso. Miradlo y decidme ^^

**Comment by DawidPelc** [comment]
Lo que está pasando es que está pasando es que la entrada 1-1 ya existe, es decir, ya hay una fotografia subida de la obra 1, tendrias que poner la ID 2. Si os sirve hemos actualizado la ayuda con dos métodos para obtener el útlimo ID de fotografia de cada obra y espacio, a ese se le suma 1 y ya tienes la nueva ID que tienes que utilizar.

**Comment by Ballesito** [comment]
En principio no por que le estaba poniendo una imagen a una obra que acababa de crear y no tenia foto dicha obra.

**Comment by DawidPelc** [comment]
Por lo que veo en la foto de antes estás subiendo una foto poniendo obra_id = 0 , y no hay ninguna obra con esa ID, acabo de probar con una existente y me ha funcionado
![image](https://user-images.githubusercontent.com/77160788/157917223-0d8e7a20-c011-4987-978d-1072ccc50b27.png)

**Comment by Ballesito** [comment]
Ya esta, gracias.
