### ISSUE TITLE
Error mínimo en iniciar sesión

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#22]
Si intento hacer el login me sale esto:
![image](https://user-images.githubusercontent.com/77398602/157891639-e43dd95b-c91f-426d-a5ed-3addae82f350.png)

**Comment by DawidPelc** [comment]
No sabemos porque sale este error, lo intentaremos solucionar

**Comment by Ballesito** [comment]
Valep, avisad cuando lo tengáis solucionado para seguir trabajando ^^

**Comment by DawidPelc** [comment]
Solucionado
