### ISSUE TITLE
Falten camps de les exposicions

### ISSUE THREAD

**Issue by sergicladeraben** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#3]
Hola bones tardes.
Revisant la API ens hem donat conta que l'endpoint de les exposicions ens falten els següents camps: una descripció per cada idioma i el conjunt de les seves obres mes rellevants. El json a retornar hauria de tenir aquests camps.
![image](https://user-images.githubusercontent.com/77398698/154317917-e95c6a48-a977-4281-a5fa-076af5ba8077.png)
Moltes gracies.

**Comment by sergicladeraben** [comment]
Revisant l'isuue he comprovat nomes falta: una descripció per cada idioma i el conjunt de les seves obres mes rellevants

**Comment by DawidPelc** [comment]
Fet, podeu comprovar el format amb l'exposició amb ID 1 que ja té dades completes http://www.dawidpelc.com/api/laravel_projecte_baleart-dawidmateujulia/public/api/exposicions/1

**Comment by sergicladeraben** [comment]
Aixi esta molt be, gràcies.
