### ISSUE TITLE
Falten camps a les obres

### ISSUE THREAD

**Issue by sergicladeraben** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#4]
Hola bones tardes.
Testejant la API ens hem donat conta que a les obres falten alguns camps, aqui teniu els camps que hauria de retornar cada una de les obres.
![image](https://user-images.githubusercontent.com/77398698/154318719-58a70566-fbee-45f6-b98b-d9715fd74f8b.png)

**Comment by spdvi** [comment]
Bones @sergicladeraben , les específicacions de la informació que ha de tenir cada entitat estàn obertes i no ténen perquè coincidir amb les que hi ha al document proporcionat, a no ser que siguin estrictament necessàries.
Si no es un camp important com per exemple el identificador d'una obra o el títol no cal que estigui. Si has de mester algun camp més els hi pots demanar si ho poden posar.
Sinò has d'adaptar la interfície a la informació que surt a la API.
En aquest cas concret fixat que codi de registre ells ho ténen com un 'id', el títol com 'nom', etc.

**Comment by sergicladeraben** [comment]
He revisat l'issue i el que s'hauria d'afegir es la fotografia de l'obra.
Tambe s'hauria de modificar perque la modalitat de l'obra i el nom de l'autor, n'aperegui el nom i no el seu id

**Comment by DawidPelc** [comment]
Fet, podeu consultar el format de l'exposició amb ID 1 ja que té dades http://www.dawidpelc.com/api/laravel_projecte_baleart-dawidmateujulia/public/api/obres/1

**Comment by sergicladeraben** [comment]
Aixi ens funcionará be, gracies.
