### ISSUE TITLE
Poder manejar las imágenes

### ISSUE THREAD

**Issue by AlexisEvol** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#5]
Falta poder hacer GET de las imágenes plz <3

**Comment by DawidPelc** [comment]
He puesto un GET a las imágenes tanto de obras como de espais que muestra todas las fotos y modificado el método de crear y subir imágenes. Ahora solo hay un POST y la imagen se sube directamente cuando creas la tupla, lo podéis consultar en el PDF de ayuda, lo vamos actualizando según añadimos los cambios.
