### ISSUE TITLE
Falten camps per els Usuaris

### ISSUE THREAD

**Issue by sergicladeraben** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#6]
Revisant els camps d'usuari he comprovat falten alguns camps, apart el camp d'admin he vist que acepta un integer volia sebre per si era per alguna cosa en especial.
Falten els camps de:
- Nom i llinatges.
- DNI
- Telefon

**Comment by sergicladeraben** [comment]
Revisant la nostre documentació hem comprovat que nomes seria necessari afegir el nom i llinatges per tal d'incorporar-ho a l'interficie

**Comment by DawidPelc** [comment]
Fet
