### ISSUE TITLE
Borrar usuarios

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#7]
He probado con un user que no tiene admin (random@paucasesnovescifp.cat) a borrar un user, en principio no debería ya que no es admin, pero lo borra iguall. Tambien cuando lo borra el user no dice nada pero lo borra, deberia de salir un mensaje de que ha ido bien o ha ido mal o algo.
![image](https://user-images.githubusercontent.com/77398602/154325140-b9d0c58b-d388-408c-a99b-8c04d36d5653.png)
 Mirad esa parte pls ^^

**Comment by DawidPelc** [comment]
Arreglado, ahora si no eres admin no puedes borrar y te sale mensaje informativo tanto cuando creas, borras o no eres administrador.
