### ISSUE TITLE
Ampliar tiempo del Token

### ISSUE THREAD

**Issue by sergicladeraben** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#8]
Hola buenas tardes,
si pudieseis ampliar el tiempo que tarda el Token en caducar, nos ayudaria para ir testeando.
A veces hacemos un par de pruebas y ya tenemos que renovar.
Muchas gracias

**Comment by DawidPelc** [comment]
El token no expira, simplemente se renueva con cada login. Lo que habrá pasado es que habreis hecho login con el mismo usuario desde diferentes máquinas y machacáis el token, usad diferentes usuarios y deberia de funcionar sin expirar hasta hacer logout.

**Comment by sergicladeraben** [comment]
Fallo nuestro, disculpa las molestias.

**Comment by DawidPelc** [comment]
Tranqui, yo tambien me acabo de enterar que se lo he preguntado al profe jaja.
