### ISSUE TITLE
No permite modificar usuarios

### ISSUE THREAD

**Issue by Ballesito** [CIFP-Pau-Casesnoves-DAW/baleart-public-dawidmateujulia#9]
Revisando la API me he dado cuenta que tanto si no eres admin (ahi normal) como si eres admin no te deja cambiar los datos de los users, he intentado crear un nuevo usuario siendo admin desde cero y aun asi no deja.
Me sale este error:
![image](https://user-images.githubusercontent.com/77398602/154533893-5583d9e1-d0d2-4801-a265-dbb27f553e5b.png)

**Comment by DawidPelc** [comment]
Según veo ahí estás usando el método PUT, y para crear es con POST, acabo de probar y he podido
![image](https://user-images.githubusercontent.com/77160788/154750445-fb034005-17c4-40ba-936a-d676ff88d5e0.png)
También he podido editar un usuario
![image](https://user-images.githubusercontent.com/77160788/154751025-b973b51e-178f-44b3-8d7b-86541157bb49.png)

**Comment by spdvi** [comment]
@Ballesito ya lo tienes solucionado? ¿Se puede cerrar el Issue?
